### ISSUE TITLE
[GraphQL Plugin] README for GraphQL Plugin

### ISSUE THREAD

**Issue by taras** [thefrontside/playhouse#66]
## TODO

- [x] Installation instructions
- [x] How to add GraphQL to GraphiQL plugin?
- [x] How to integrate with Backstage API Docs Plugin?
- [x] How to use built in directives?
- [ ] How to extract the schema?
- [x] How do you extend the schema from `packages/backstage/src/plugins/graphql`?
- [ ] How to extend schema from a plugin?
- [ ] How to add new directives?
- [ ] How to connect to the GraphQL API from the frontend?
- [ ] How to test the GraphQL API?
